from django.urls import path
from . import views

urlpatterns = [
    path('ffem',views.ffem,name='ffem'),
    path('ffec',views.ffec,name='ffec'),
    path('ffemh',views.ffemh,name='ffemh'),
    path('ffcp',views.ffcp,name='ffcp'),
    path('fsem',views.fsem,name='fsem'),
    path('fsep',views.fsep,name='fsep'),
    path('fseg',views.fseg,name='fseg'),
    path('fscs',views.fscs,name='fscs'),
    path('stem',views.stem,name='stem'),
    path('stdm',views.stdm,name='stdm'),
    path('stds',views.stds,name='stds'),
    path('stca',views.stca,name='stca'),
    path('sfda',views.sfda,name='sfda'),
    path('sfps',views.sfps,name='sfps'),
    path('sfos',views.sfos,name='sfos'),
    path('sfpd',views.sfpd,name='sfpd'),
    path('tfds',views.tfds,name='tfds'),
    path('tftc',views.tftc,name='tftc'),
    path('tfml',views.tfml,name='tfml'),
    path('tfcl',views.tfcl,name='tfcl'),
    path('tscd',views.tscd,name='tscd'),
    path('tscn',views.tscn,name='tscn'),
    path('tsai',views.tsai,name='tsai'),
    path('tsiot',views.tsiot,name='tsiot'),
    path('fsvse',views.fsvse,name='fsvse'),
    path('fsvds',views.fsvds,name='fsvds'),
    path('fsvcc',views.fsvcc,name='fsvcc'),
    path('fsvbt',views.fsvbt,name='fsvbt'),
    path('fegdp',views.fegdp,name='fegdp'),
    path('fegcn',views.fegcn,name='fegcn'),
    path('exam',views.exam,name='exam'),
]